# ---------------------------------------------------------------------
# Kubernetes Deployment: whoami
# ---------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: whoami
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami:v1.10.0
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

---
# ---------------------------------------------------------------------
# Kubernetes Service
# ---------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: whoami-svc
  namespace: whoami
spec:
  type: ClusterIP
  selector:
    app: whoami
  ports:
    - port: 80
      targetPort: 80

---
# ---------------------------------------------------------------------
# Kubernetes Ingress (Traefik + Let's Encrypt automatic)
# ---------------------------------------------------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-ingress
  namespace: whoami
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  ingressClassName: traefik
  rules:
  - host: whoami.digitalepalika.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami-svc
            port:
              number: 80
  tls:
  - hosts:
    - whoami.digitalepalika.com

---
# ---------------------------------------------------------------------
# Bootstrap Declaration for persistence and ownership
# ---------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: whoami-bootstrap-manifest
  namespace: whoami
data:
  managedBy: "system-bootstrap"
  path: "/etc/system-bootstrap/whoami/whoami.yaml"
  applied: "true"
